# Generated by Django 4.0.4 on 2022-05-18 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formapagamento',
            old_name='status',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='grupodespesa',
            old_name='status',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='tipodespesa',
            old_name='status',
            new_name='ativo',
        ),
    ]
